### ISSUE TITLE
Ssh

### ISSUE THREAD

**Issue by Adityapro9** [kcubeterm/kali-web#1]
How to connect ssh

**Comment by kcubeterm** [comment]
for ssh you must have to establishing tunnels with the help of services like ngrok

**Comment by Adityapro9** [comment]
App will suspend

**Comment by kcubeterm** [comment]
for that you can keep pinging the main url every 29 minutes. it will prevent from sleeping but against the terms and conditions probably

**Comment by Adityapro9** [comment]
Sudo command have error

**Comment by kcubeterm** [comment]
its uses fakeroot and chroot. wondering why will sudo work here. and whats the benefits.
